FROM debian:bookworm-slim

ARG TARGETPLATFORM
ARG TARGETARCH

RUN apt-get update \
    && packages="ca-certificates libvirt-clients nut-client" \
    && if [ "$TARGETARCH" = "amd64" ]; then packages="$packages intel-gpu-tools"; fi \
    && apt-get install --no-install-recommends -y $packages \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY $TARGETPLATFORM/ugos-bridge /usr/local/bin/ugos-bridge

EXPOSE 9877

ENTRYPOINT ["/usr/local/bin/ugos-bridge"]

